
services:
  # 服务名：db (数据库)
  db:
    # 镜像：这里关键！我们不用官方的 postgres，而是用 postgis/postgis
    # 这样你就直接拥有了 GIS 处理能力，不用自己去装插件
    image: postgis/postgis:15-3.3
    
    # 容器崩溃后自动重启，保证高可用
    restart: always
    
    # 环境变量：设置账号密码
    environment:
      POSTGRES_USER: mleKiller      # 你的用户名
      POSTGRES_PASSWORD: 1 # 你的密码 (开发环境随便写，生产环境要复杂)
      POSTGRES_DB: awareness_db    # 数据库名字
    
    # 端口映射：把容器里的 5432 暴露给宿主机
    # 这样你的 Python 代码或者 DBeaver 才能连进去
    ports:
      - "5432:5432"
    
    # 数据卷：持久化存储
    # 把容器里的 /var/lib/postgresql/data 映射到你当前目录下的 pg_data 文件夹
    # 这样删了容器，数据还在！
    volumes:
    # 新写法: 使用具名卷
      - postgres_data:/var/lib/postgresql/data

# 定义具名卷
volumes:
  postgres_data:

  # 未来这里还会加 Redis, Nginx 等服务...